version: "3"
services:
  scoretracker:
    container_name: scoretracker
    build: ./app
    env_file:
      - .env
    volumes:
      - res:/resultat

volumes:
  res:
    driver: local
    name: res
    driver_opts:
      type: none
      o: bind
      device: ./resultat
